version: 2

sources:
- name: caps_cfs
  database: "{{target.name}}__fivetran"
  tables:
    - name: accounting_dealership_ledgers
    - name: accounting_invoices
    - name: accounting_invoices_line_items
    - name: accounting_line_items
    - name: ach_accounts
    - name: ach_prenotes
    - name: addresses
    - name: affiliates
    - name: applications
    - name: artifacts
    - name: authentication_tokens
    - name: authorized_people
    - name: bank_accounts
    - name: bookings
    - name: boosts
    - name: cancellation_reasons
    - name: cash_offer_eligibilities
    - name: child_oems
    - name: cip_verifications
    - name: comments
    - name: credit_declines
    - name: credit_line_increases
    - name: credit_pulls
    - name: customer_invites
    - name: dealership_affiliates
    - name: dealership_child_oems
    - name: dealership_enrolled_programs
    - name: dealerships
    - name: dealerships_groups
    - name: dealerships_users
    - name: distributors
    - name: distributors_users
    - name: documents
    - name: drivers_licenses
    - name: email_transactions
    - name: employments
    - name: enrolled_programs
    - name: fivetran_audit
    - name: groups
    - name: groups_users
    - name: identifications
    - name: identity_verifications
    - name: inquiries
    - name: internal_comments
    - name: loan_boardings
    - name: loan_fundings
    - name: loan_packages
    - name: loan_transfers
    - name: loans
    - name: makes
    - name: managers
    - name: markets
    - name: models
    - name: nacha_files
    - name: nacha_return_files
    - name: nls_boardings
    - name: notes
    - name: parent_oems
    - name: partner_bonuses
    - name: pay_near_mes
    - name: phone_codes
    - name: phones
    - name: plaid_auths
    - name: plaid_items
    - name: portfolios
    - name: preciseid_requests
    - name: premier_attributes
    - name: prequals
    - name: purchase_boardings
    - name: recurring_payments
    - name: refunds
    - name: repairs
    - name: revolver_cards
    - name: roles
    - name: roles_users
    - name: tabapay_accounts
    - name: tabapay_cards
    - name: tabapay_transactions
    - name: tci_boardings
    - name: team_comments
    - name: tlo_person_records
    - name: tlo_person_searches
    - name: tlo_vehicle_records
    - name: tlo_vehicle_searches
    - name: transactions
    - name: transmissions
    - name: user_connections
    - name: users
    - name: utm_parameter_sets
    - name: vehicles
    - name: verification_records
    - name: western_union_accounts