version: 2

sources:
  - name: CAPS
    database: DBT_DB
    schema: CAPS
    tables:
      - name: DEALERSHIP_AFFILIATES
        description: "The table storing information about dealership affiliates."
        
      - name: AFFILIATES
        description: "The table storing affiliate information."
