data_pipeline:
  outputs:
    dev:
      account: QKTSPVQ-THB27726
      database: DBT_DB
      password: Arvind19691998
      role: DBT_ROLE
      schema: DBT_SCHEMA
      threads: 6
      type: snowflake
      user: DEEPAKMISHRA
      warehouse: DBT_WH
  target: dev