data_pipeline:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ secrets.SNOWFLAKE_ACCOUNT }}"  # Must be string
      user: "{{ secrets.SNOWFLAKE_USER }}"        # Must be string
      password: "{{ secrets.SNOWFLAKE_PASSWORD }}"# Must be string
      role: "{{ secrets.SNOWFLAKE_ROLE }}"        # Must be string
      database: "{{ secrets.SNOWFLAKE_DATABASE }}"# Must be string
      warehouse: "{{ secrets.SNOWFLAKE_WAREHOUSE }}" # Must be string
      schema: "{{ secrets.SNOWFLAKE_SCHEMA }}"    # Must be string
      threads: 4
      client_session_keep_alive: False