data_pipeline:
  outputs:
    dev:
      account: QKTSPVQ-THB27726
      database: DBT_DB
      password: Arvind19691998
      role: DBT_ROLE
      schema: DBT_SCHEMA
      threads: 6
      type: snowflake
      user: DEEPAKMISHRA
      warehouse: DBT_WH
  target: dev
lens_project:
  outputs:
    dev:
      account: OKOGVXX-PRODUCTION
      client_session_keep_alive: false
      database: DEV_LAKE_LENS
      password: BN@th1969
      query_tag: dbt
      role: LENS_DEV_ROLE
      schema: CAPS
      threads: 4
      type: snowflake
      user: DEV__DEEPAKMISHRA
      warehouse: LENS_WH
  target: dev
