version: 2

sources:
  - name: tpch
    database: snowflake_sample_data
    schema: tpch_sf1
    tables:
      - name: orders
        columns:
          - name: o_orderkey
            tests:
              - unique
              - not_null
      - name: lineitem
        columns:
          - name: l_orderkey
            tests:
              - relationships:
                  to: source('tpch', 'orders')
                  field: o_orderkey
  - name: DBT_DB
    database: DBT_DB
    schema: CAPS
    tables:
      - name: DEALERSHIP_AFFILIATES1
        description: "The table storing information about dealership affiliates."
        
      - name: AFFILIATES1
        description: "The table storing affiliate information."